name: Build and Deploy
on:
  push:
    branches:
      - 'master'
      - 'main'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        run: |
          make install-python-requirements
          make generate-site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: 2021/site
