name: Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        run: |
          make install-python-requirements
          make install-python-requirements-test
          make generate-site
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and Build
        run: |
          make install-python-requirements
          make install-python-requirements-test
          make generate-site
      - name: Links validation
        run: make check-links
